contrate_frontend:
    resource: "@ContrateFrontendBundle/Resources/config/routing.yml"
    prefix:   /

contrate_backend:
    resource: "@ContrateBackendBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /perfil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /cadastro

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /perfil

#_imagine:
#    resource: .
#    type:     imagine

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
