contrate_frontend_homepage:
    path:     /
    defaults: { _controller: ContrateFrontendBundle:Default:index }

ContrateBackendBundle_artist:
        resource: "@ContrateBackendBundle/Resources/config/routing/artist.yml"
        prefix:   /artista

contrate_frontend_search:
    path:     /busca/{category}
    defaults: { _controller: ContrateFrontendBundle:Default:search, 'category': null }

ContrateBackendBundle_contact:
        resource: "@ContrateBackendBundle/Resources/config/routing/contact.yml"
        prefix:   /contato

contrate_frontend_quem:
    path:     /quem-somos
    defaults: { _controller: ContrateFrontendBundle:Default:quem }

contrate_frontend_duvidas:
    path:     /duvidas
    defaults: { _controller: ContrateFrontendBundle:Default:duvidas }

contrate_frontend_como:
    path:     /como-funciona
    defaults: { _controller: ContrateFrontendBundle:Default:como }